//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "components")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub version: String,
    pub revision: String,
    pub anitya_id: Option<String>,
    pub repology_id: Option<String>,
    pub project_url: Option<String>,
    pub gate_id: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub recipe: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub patches: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub scripts: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::archives::Entity")]
    Archives,
    #[sea_orm(
        belongs_to = "super::gates::Entity",
        from = "Column::GateId",
        to = "super::gates::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Gates,
}

impl Related<super::archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Archives.def()
    }
}

impl Related<super::gates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gates.def()
    }
}
