apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-forged
  labels:
    app: forged
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: forged
  template:
    metadata:
      labels:
        app: forged
    spec:
      containers:
        - name: forged
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          env:
            - name: FORGED__POSTGRES__URL
              value: {{ .Values.postgres.url | quote }}
            - name: FORGED__SEAWEEDFS__MASTER_URL
              value: {{ .Values.seaweedfs.masterUrl | quote }}
            - name: FORGED__AMQP__URL
              value: {{ .Values.amqp.url | quote }}
            - name: RUST_LOG
              value: {{ .Values.env.RUST_LOG | quote }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
