[package]
name = "forge"
version.workspace = true
edition.workspace = true

[workspace.package]
version = "0.1.0"
edition = "2021"

[dependencies]
github.workspace = true
miette.workspace = true
thiserror.workspace = true
serde.workspace = true
url.workspace = true

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
thiserror = "1.0.50"
miette = "5.10.0"
config = "0.13.3"
deadpool-lapin = { version = "0.11.0", features = ["serde"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.33.0", features = ["full", "tracing"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["json", "tracing", "env-filter"] }
axum = { version = "0.6.20", features = ["tracing"] }
clap = { version = "4.4.7", features = ["derive"] }
hyper = "0.14.27"
github = { version = "*", path = "crates/github" }
strum = { version = "0.25.0", features=["derive"] }
forge = { version = "*", path = "." }
url = { version = "2.4.1", features = ["serde"] }
