services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "forged"
      POSTGRES_USER: "forged"
      POSTGRES_DB: "forged"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  seaweedfs-master:
    image: chrislusf/seaweedfs:latest
    ports:
      - "9333:9333"
    command: "master -ip=seaweedfs-master"
    volumes:
      - "seaweedfs-master:/data"

  seaweedfs-volume:
    image: chrislusf/seaweedfs:latest
    ports:
      - "8080:8080"
    command: "volume -mserver=seaweedfs-master:9333 -port=8080 -publicUrl=localhost:8080"
    depends_on:
      - seaweedfs-master
    volumes:
      - "seaweedfs-volume:/data"

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_VHOST: "master"
      RABBITMQ_DEFAULT_USER: "dev"
      RABBITMQ_DEFAULT_PASS: "dev"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  postgres: {}
  seaweedfs-master: {}
  seaweedfs-volume: {}
  rabbitmq: {}
