version: '3.9'

services:  
  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_VHOST: "master"
      RABBITMQ_DEFAULT_USER: "dev"
      RABBITMQ_DEFAULT_PASS: "dev"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "forge"
      POSTGRES_USER: "forge"
      POSTGRES_DB: "forge"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  garage:
    image: dxflrs/garage:v0.9.3
    ports:
      - "3900:3900"
      - "3902:3902"
      - "3903:3903"
      - "3904:3904"
    volumes:
      - "./sample_data/garage.toml:/etc/garage.toml"
      - "garage-meta:/var/lib/garage/meta/"
      - "garage-data:/var/lib/garage/data/"

volumes:
  rabbitmq: {}
  postgres: {}
  garage-meta: {}
  garage-data: {}
