version: '3.9'

services:  
  rabbitmq:
    image: rabbitmq:3.12-management
    networks:
      - server
    environment:
      RABBITMQ_DEFAULT_VHOST: "master"
      RABBITMQ_DEFAULT_USER: "dev"
      RABBITMQ_DEFAULT_PASS: "dev"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 8090:15672
      - 5672:5672

  postgres:
    image: postgres:16-bookworm
    networks:
      - server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "forge"
      POSTGRES_USER: "forge"
      POSTGRES_DB: "forge"
    volumes:
      - "postgres:/var/lib/postgresql/data"

networks:
  client: {}
  server: {}

volumes:
  rabbitmq: {}
  postgres: {}
