//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "push_to_component_record")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub push_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub component_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::component::Entity",
        from = "Column::ComponentId",
        to = "super::component::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Component,
    #[sea_orm(
        belongs_to = "super::source_repo_push::Entity",
        from = "Column::PushId",
        to = "super::source_repo_push::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SourceRepoPush,
}

impl Related<super::component::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Component.def()
    }
}

impl Related<super::source_repo_push::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SourceRepoPush.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::component::Entity")]
    Component,
    #[sea_orm(entity = "super::source_repo_push::Entity")]
    SourceRepoPush,
}
