//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "recipe_kind")]
pub enum RecipeKind {
    #[sea_orm(string_value = "forge")]
    Forge,
    #[sea_orm(string_value = "open_indiana_userland")]
    OpenIndianaUserland,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "source_repo_kind")]
pub enum SourceRepoKind {
    #[sea_orm(string_value = "recipes")]
    Recipes,
    #[sea_orm(string_value = "upstream")]
    Upstream,
}
