//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "source_repo_push")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub repository_id: Uuid,
    pub r#ref: String,
    pub sha256: String,
    pub url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::push_to_component_record::Entity")]
    PushToComponentRecord,
}

impl Related<super::push_to_component_record::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PushToComponentRecord.def()
    }
}

impl Related<super::component::Entity> for Entity {
    fn to() -> RelationDef {
        super::push_to_component_record::Relation::Component.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::push_to_component_record::Relation::SourceRepoPush
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::push_to_component_record::Entity")]
    PushToComponentRecord,
    #[sea_orm(entity = "super::component::Entity")]
    Component,
}
