[package]
name = "prisma"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prisma-client-rust.workspace = true
prisma-client-rust-cli.workspace = true
serde.workspace = true
