[package]
name = "pkgdev"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
component.workspace = true
integration.workspace = true
thiserror.workspace = true
miette = { workspace = true, features = ["fancy"] }
config.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
clap = { workspace = true, features = ["derive"] }
strum.workspace = true
reqwest = { version = "0.11.24", features = ["blocking", "rustls-tls"], default-features = false }
workspace = { version = "*", path = "../workspace" }
repology.workspace = true
semver = { version = "1.0.22", features = ["serde"] }
gate.workspace = true