metadata_dir = "/var/lib/garage/meta/"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

replication_mode = "none"

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "dde567b9f73a1acecda56dbf913d9dfa615e5fd6ef5316df171f8402e187b2e9"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.local"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.local"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "bvFIZ8pGf0myXP4r1NqH/VbNHFzqDfAw0RTznSxS4gY="
metrics_token = "KrsZ/ELXGBq6d7UPSQfYb+N2uMMv8oBbIhejGJX41pc="
